name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - run: uv sync --extra dev

      - run: uv run pytest --cov=heormodel --cov-report=xml

      - run: uv run pytest --doctest-modules src --cov=heormodel --cov-report=xml --cov-append

      - uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: false
